### ISSUE TITLE
Condition Column not working in Apex 22.1

### ISSUE THREAD

**Issue by marnusv** [foex-open-source/fos-interactive-grid-add-button#10]
When a button is assigned to "Menu - Row Actions" with a Condition Column defined the following JS exception gets raised and the buttons don't render.
`
interactiveGrid.min.js?v=22.1.0:1 Uncaught TypeError: Cannot read properties of undefined (reading '10')
    at Object.getValue (interactiveGrid.min.js?v=22.1.0:1:23964)
    at HTMLDivElement.<anonymous> (script.js:316:40)
    at HTMLDivElement.dispatch (desktop_all.min.js?v=22.1.0:2:43064)
    at HTMLDivElement.v.handle (desktop_all.min.js?v=22.1.0:2:41048)
    at Object.trigger (desktop_all.min.js?v=22.1.0:2:71515)
    at HTMLDivElement.<anonymous> (desktop_all.min.js?v=22.1.0:2:72110)
    at Function.each (desktop_all.min.js?v=22.1.0:2:3003)
    at s.fn.init.each (desktop_all.min.js?v=22.1.0:2:1481)
    at s.fn.init.trigger (desktop_all.min.js?v=22.1.0:2:72086)
    at q.<computed>.<computed>._trigger (desktop_all.min.js?v=22.1.0:29:9569)
getValue @ interactiveGrid.min.js?v=22.1.0:1
(anonymous) @ script.js:316
dispatch @ desktop_all.min.js?v=22.1.0:2
v.handle @ desktop_all.min.js?v=22.1.0:2
trigger @ desktop_all.min.js?v=22.1.0:2
(anonymous) @ desktop_all.min.js?v=22.1.0:2
each @ desktop_all.min.js?v=22.1.0:2
each @ desktop_all.min.js?v=22.1.0:2
trigger @ desktop_all.min.js?v=22.1.0:2
_trigger @ desktop_all.min.js?v=22.1.0:29
M @ desktop_all.min.js?v=22.1.0:47
open @ desktop_all.min.js?v=22.1.0:47
a.<computed> @ desktop_all.min.js?v=22.1.0:29
toggle @ desktop_all.min.js?v=22.1.0:47
a.<computed> @ desktop_all.min.js?v=22.1.0:29
(anonymous) @ desktop_all.min.js?v=22.1.0:29
each @ desktop_all.min.js?v=22.1.0:2
each @ desktop_all.min.js?v=22.1.0:2
q.fn.<computed> @ desktop_all.min.js?v=22.1.0:29
n @ desktop_all.min.js?v=22.1.0:47
(anonymous) @ desktop_all.min.js?v=22.1.0:47
dispatch @ desktop_all.min.js?v=22.1.0:2
v.handle @ desktop_all.min.js?v=22.1.0:2
`
When the condition is removed the buttons render as per normal.

**Comment by foex-open-source** [comment]
Thanks for making us aware of this issue

The FOS plug-ins are not compatible with 22.1 yet, we're working on it,  the release will happen soon.

In the meantime, you could fix it just by replacing a line in the **js/script.js** file.

Line 317:
`var record = grid.getContextRecord(grid.view$.find('.js-menuButton.is-active'))[0];`

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/61969891/167768130-1ce96ac7-eea3-4ef7-ab65-add802f75561.png">

**Comment by marnusv** [comment]
Thank you for the prompt response. The recommended changed fixed the issue.
