### ISSUE TITLE
Conditional buttons in row action menus are broken in APEX 22.1

### ISSUE THREAD

**Issue by Mabktst** [foex-open-source/fos-interactive-grid-add-button#11]
Hi, 

Example 6 on https://fos.world/ords/f?p=10000:2010 does not work with APEX 22.1 as the row action button has no class "js-menuButton" set anymore. This class is called 'a-Button--actions' in the latest universal theme. 

It can be easily fixed by changing js-menuButton to a-Button--actions in line 317 of script.js:
// this is how we get the record associated to the currently opened row actions menu
var record = grid.getContextRecord(grid.view$.find('.a-Button--actions.is-active'))[0]; // js-menuButton

I've noticed, that this plugin has no confirmed APEX 22.1 compatibility yet, but I hope this might help anyway.

Regards
Michael

**Comment by foex-open-source** [comment]
Hi Michael, thanks for reporting the issue, it's been implemented already with #10.

**Comment by Mabktst** [comment]
Ah, I should have checked the closed issues before raising a new one. Sorry for that!
