### ISSUE TITLE
Not Respecting Theme Custom Prefix Class

### ISSUE THREAD

**Issue by martindsouza** [foex-open-source/fos-interactive-grid-add-button#6]
I'm using FontAwesome instead of Font Apex and trying to use the FontAwesome 5.x prefix (ie `far` instead of `fa`). 

Theme setting is as follows:

<img width="782" alt="Screen Shot 2021-02-03 at 3 59 40 PM" src="https://user-images.githubusercontent.com/2925726/106820826-46af6180-6639-11eb-8fff-08534d511fff.png">

Note the setting of the `Custom Prefix Class` is set to `far` (this could be `fal`, `fas`, etc.)

The plugin is use `fa` by default and should use the `Custom Prefix Class` when defined.

Current workaround: in FontAwesome I'm using the FA Kit. I've set it to be 4.x backwards compatible:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/2925726/106820936-7bbbb400-6639-11eb-8509-ecaee8e0238f.png">

**Comment by stefandobre** [comment]
Thanks Martin for bringing this up. This should indeed get fixed.
I will update this issue as soon as it's done.

**Comment by foex-open-source** [comment]
Fixed in just published v21.1.0
